'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { motion } from 'framer-motion';

const articles: Record<string, { category: string; title: string; read: string; image: string; intro: string; sections: { heading: string; body: string }[] }> = {
  'dubai-five-day-guide': { category: 'Destination guides', title: 'How to Spend Five Unforgettable Days in Dubai', read: '6 min read', image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=2200&q=85', intro: 'Dubai rewards a little balance. Give the major sights their moment, then leave enough room for the city beyond them.', sections: [{ heading: 'Start with the skyline', body: 'Begin around Downtown and give yourself time to experience Dubai from different perspectives. The scale of the architecture is part of the experience, but it becomes more interesting when you slow down enough to notice the details around it.' }, { heading: 'Make room for the desert', body: 'A desert experience changes the rhythm of a city break. Set aside a day or evening for the landscape outside the city, rather than trying to fill every hour with another attraction.' }, { heading: 'Leave space for your own discoveries', body: 'The strongest itineraries are not packed from morning to night. Keep time for a long meal, a marina walk, shopping, or simply returning to somewhere you enjoyed earlier.' }] },
  'when-to-plan-your-next-trip': { category: 'Travel planning', title: 'When Is the Best Time to Plan Your Next Trip?', read: '5 min read', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=2200&q=85', intro: 'There is rarely one perfect travel month. The better question is what you want the trip to feel like.', sections: [{ heading: 'Start with the experience', body: 'Weather matters, but so do events, crowds, daylight, local atmosphere and the activities you want to experience. Choose the experience first, then work backwards into dates.' }, { heading: 'Consider the trade-offs', body: 'Peak periods can bring energy and major events, while shoulder seasons can offer a quieter pace. Neither is automatically better; it depends on the journey you are building.' }, { heading: 'Plan before the obvious rush', body: 'The earlier you understand your preferred dates, the more options you have for accommodation, flights and experiences. Good planning creates flexibility rather than simply creating a longer checklist.' }] },
  'a-different-way-to-experience-london': { category: 'City guides', title: 'A Different Way to Experience London', read: '7 min read', image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=2200&q=85', intro: 'London becomes more interesting when you stop trying to see all of it at once.', sections: [{ heading: 'See the landmarks, then move on', body: 'The classic sights deserve their place, but they should not define the entire trip. Once you have seen what brought you to London, give yourself permission to wander.' }, { heading: 'Choose neighbourhoods over checklists', body: 'A morning in one neighbourhood can reveal more about the city than crossing five attractions off a list. Markets, cafés, galleries and parks are often where the atmosphere lives.' }, { heading: 'Keep one day deliberately open', body: 'An unscheduled day creates room for recommendations, weather changes and those places you discover only after arriving.' }] },
  'why-some-journeys-stay-with-you-longer': { category: 'Travel notes', title: 'Why Some Journeys Stay With You Longer', read: '4 min read', image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=85', intro: 'The trips we remember most clearly are rarely just collections of famous places.', sections: [{ heading: 'It is often the unexpected detail', body: 'A quiet street, an excellent meal, a conversation or an unplanned detour can become more memorable than the landmark you travelled across the world to see.' }, { heading: 'Pace changes memory', body: 'When every hour is accounted for, there is little room for the experience to breathe. A little empty space can make the moments around it feel more significant.' }, { heading: 'Plan enough to be free', body: 'Good travel planning is not about controlling every moment. It is about removing avoidable friction so you have more freedom to enjoy the moments that cannot be planned.' }] },
  'cape-town-mountains-coastlines-and-more': { category: 'Destination guides', title: 'Cape Town: Mountains, Coastlines and More', read: '8 min read', image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=2200&q=85', intro: 'Cape Town is one of those destinations where the landscape becomes part of the itinerary.', sections: [{ heading: 'Begin with the city', body: 'Give yourself time to experience Cape Town as a city before heading further out. Its food, neighbourhoods and cultural spaces provide a strong starting point.' }, { heading: 'Follow the coast', body: 'The coastline creates a natural reason to slow down. Build time for scenic routes and viewpoints rather than treating them as quick stops between activities.' }, { heading: 'Go beyond the obvious', body: 'The surrounding winelands and wider Cape landscape make it possible to build several different kinds of journeys around the same destination.' }] },
  'tokyo-a-guide-to-going-slowly': { category: 'City guides', title: 'Tokyo: A Guide to Going Slowly', read: '6 min read', image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=2200&q=85', intro: 'Tokyo can feel overwhelming if you try to experience all of it. The better approach may be to choose less.', sections: [{ heading: 'Pick a few areas', body: 'Instead of crossing the city repeatedly, spend meaningful time in a handful of neighbourhoods. Tokyo changes character quickly, and that contrast is part of its appeal.' }, { heading: 'Follow your curiosity', body: 'Leave room for small restaurants, quiet streets, temples and shops that were never part of the original plan. These details often become the strongest memories.' }, { heading: 'Let the city set the pace', body: 'Tokyo is precise and fast, but there is no requirement for your trip to be. Build slower mornings and open afternoons into the journey.' }] },
};

const fadeUp = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] } } };

export default function BlogArticlePage() {
  const params = useParams();
  const slug = typeof params.slug === 'string' ? params.slug : '';
  const article = articles[slug];

  if (!article) return <main className="grid min-h-screen place-items-center bg-[#f4f1e9] px-6 text-center text-[#181611]"><div><p className="text-sm text-[#181611]/50">Story not found</p><Link href="/blog" className="mt-5 inline-block underline">Back to journal</Link></div></main>;

  return (
    <main className="min-h-screen bg-[#f4f1e9] text-[#181611]">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 md:px-10"><Link href="/" className="font-serif text-2xl">TravelQ.</Link><Link href="/blog" className="text-sm text-[#181611]/60 hover:text-[#181611]">← Journal</Link></nav>
      <header className="mx-auto max-w-7xl px-6 pb-16 pt-14 md:px-10 md:pb-24 md:pt-20"><motion.div initial="hidden" animate="visible" variants={fadeUp} className="max-w-5xl"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#181611]/45">{article.category} · {article.read}</p><h1 className="mt-6 font-serif text-5xl font-medium leading-[0.94] tracking-tight sm:text-7xl lg:text-[7rem]">{article.title}</h1><p className="mt-8 max-w-2xl font-serif text-2xl leading-tight text-[#181611]/65 sm:text-3xl">{article.intro}</p></motion.div></header>
      <div className="mx-auto max-w-7xl px-6 md:px-10"><div className="overflow-hidden rounded-2xl"><img src={article.image} alt={article.title} className="aspect-[16/8] w-full object-cover" /></div></div>
      <article className="mx-auto max-w-4xl px-6 py-20 md:py-28"><div className="space-y-16">{article.sections.map((section, i) => <motion.section key={section.heading} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeUp}><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#181611]/35">0{i + 1}</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">{section.heading}</h2><p className="mt-6 text-lg leading-8 text-[#181611]/65">{section.body}</p></motion.section>)}</div></article>
      <section className="bg-[#181611] px-6 py-24 text-[#f4f1e9] md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#f4f1e9]/40">Keep exploring</p><h2 className="mt-6 max-w-3xl font-serif text-5xl leading-tight sm:text-7xl">Ready to turn an idea into a journey?</h2><Link href="/enquire" className="mt-9 inline-flex rounded-full bg-[#f4f1e9] px-7 py-4 text-[12px] font-semibold uppercase tracking-[0.1em] text-[#181611]">Start an enquiry ↗</Link></div></section>
    </main>
  );
}
