"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import ScrollNav from "@/components/ScrollNav";

const ease = [0.22, 1, 0.36, 1] as const;
const articles = [
  { slug: "dubai-five-day-guide", category: "Destination guides", title: "How to Spend Five Unforgettable Days in Dubai", excerpt: "A considered guide to experiencing the city beyond the obvious stops.", read: "6 min read", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=85" },
  { slug: "when-to-plan-your-next-trip", category: "Travel planning", title: "When Is the Best Time to Plan Your Next Trip?", excerpt: "A practical way to think about seasons, events, prices and the experience you actually want.", read: "5 min read", image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=85" },
  { slug: "a-different-way-to-experience-london", category: "City guides", title: "A Different Way to Experience London", excerpt: "Look beyond the checklist and give yourself time to discover the city at your own pace.", read: "7 min read", image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=85" },
  { slug: "why-some-journeys-stay-with-you-longer", category: "Travel notes", title: "Why Some Journeys Stay With You Longer", excerpt: "The places we remember are rarely defined by a single landmark.", read: "4 min read", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85" },
  { slug: "cape-town-mountains-coastlines-and-more", category: "Destination guides", title: "Cape Town: Mountains, Coastlines and More", excerpt: "A closer look at one of the world's most visually diverse city destinations.", read: "8 min read", image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1200&q=85" },
  { slug: "tokyo-a-guide-to-going-slowly", category: "City guides", title: "Tokyo: A Guide to Going Slowly", excerpt: "Why the best way to see the city might be to plan less of it.", read: "6 min read", image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=85" },
];
const categories = ["All stories", "Destination guides", "Travel planning", "City guides", "Travel notes"];
const fadeUp = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease } } };

export default function JournalPage() {
  const [category, setCategory] = useState("All stories");
  const [featured, ...restAll] = articles;
  const rest = useMemo(() => restAll.filter((a) => category === "All stories" || a.category === category), [category, restAll]);

  return (
    <main className="min-h-screen bg-[#f4f1e9] text-[#181611]">
      <ScrollNav />
      <section className="mx-auto max-w-7xl px-6 pb-14 pt-28 md:px-10 md:pb-16 md:pt-32"><motion.div initial="hidden" animate="visible" variants={fadeUp} className="max-w-4xl"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#181611]/45">TravelQ journal</p><h1 className="mt-5 font-serif text-5xl font-medium leading-[0.94] tracking-tight sm:text-7xl">Stories for<br /><span className="italic">the journey.</span></h1><p className="mt-8 max-w-xl text-[15px] leading-relaxed text-[#181611]/60 md:text-[16px]">Destination ideas, travel notes and useful perspectives for curious travellers.</p></motion.div></section>
      <section className="sticky top-[57px] z-30 border-y border-[#181611]/10 bg-[#f4f1e9]/95 backdrop-blur-md"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto px-6 py-4 md:px-10">{categories.map((c) => <button key={c} onClick={() => setCategory(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-[11px] font-semibold uppercase tracking-[0.1em] transition ${category === c ? "bg-[#181611] text-[#f4f1e9]" : "bg-white text-[#181611]/55 hover:text-[#181611]"}`}>{c}</button>)}</div></section>
      <section className="mx-auto max-w-7xl px-6 py-16 md:px-10 md:py-20"><Link href={`/blog/${featured.slug}`} className="group grid gap-8 border-b border-[#181611]/10 pb-16 lg:grid-cols-[1.15fr_0.85fr] lg:items-end"><div className="overflow-hidden rounded-2xl"><img src={featured.image} alt={featured.title} className="aspect-[16/10] w-full object-cover transition duration-700 group-hover:scale-[1.03]" /></div><div className="lg:pb-4"><p className="text-[11px] font-semibold uppercase tracking-[0.15em] text-[#181611]/40">Featured story / {featured.read}</p><h2 className="mt-5 font-serif text-4xl font-medium leading-tight tracking-tight sm:text-6xl">{featured.title}</h2><p className="mt-5 max-w-lg text-[15px] leading-relaxed text-[#181611]/60">{featured.excerpt}</p><span className="mt-7 inline-flex items-center gap-3 text-[13px] font-semibold">Read story <span>↗</span></span></div></Link></section>
      <section className="mx-auto max-w-7xl px-6 pb-24 md:px-10 md:pb-32">{rest.length === 0 ? <p className="py-16 text-center text-[14px] text-[#181611]/45">No stories in this category yet.</p> : <div className="grid gap-x-8 gap-y-14 md:grid-cols-2 lg:grid-cols-3">{rest.map((article, i) => <motion.article key={article.slug} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.15 }} variants={fadeUp} transition={{ delay: (i % 3) * 0.08 }}><Link href={`/blog/${article.slug}`} className="group block"><div className="overflow-hidden rounded-2xl"><img src={article.image} alt={article.title} className="aspect-[4/3] w-full object-cover transition duration-700 group-hover:scale-[1.04]" /></div><p className="mt-5 text-[11px] font-semibold uppercase tracking-[0.15em] text-[#181611]/40">{article.category} · {article.read}</p><h2 className="mt-2 font-serif text-2xl font-medium leading-tight tracking-tight">{article.title}</h2><p className="mt-2 text-[14px] leading-relaxed text-[#181611]/60">{article.excerpt}</p><span className="mt-4 inline-flex items-center gap-2 text-[13px] font-semibold">Read story ↗</span></Link></motion.article>)}</div>}</section>
      <section className="bg-[#181611] px-6 py-24 text-[#f4f1e9] md:px-10 md:py-32"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeUp} className="mx-auto max-w-7xl text-center"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#f4f1e9]/45">Keep exploring</p><h2 className="mx-auto mt-6 max-w-4xl font-serif text-4xl font-medium leading-tight tracking-tight sm:text-6xl">A good trip often starts with a little curiosity.</h2><Link href="/destinations" className="mt-9 inline-flex w-fit items-center gap-3 rounded-full bg-[#f4f1e9] px-6 py-3.5 text-[12px] font-semibold uppercase tracking-[0.1em] text-[#181611] transition hover:opacity-85">Explore destinations <span>↗</span></Link></motion.div></section>
      <footer className="bg-[#f4f1e9] px-6 py-12 text-[#181611] md:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-10 border-b border-[#181611]/10 pb-10 md:flex-row"><div><p className="text-[14px] font-semibold tracking-tight">TRAVELQ</p><p className="mt-3 max-w-sm text-[13px] leading-relaxed text-[#181611]/50">Curated journeys and destinations worth travelling for.</p></div><div className="grid grid-cols-2 gap-x-12 gap-y-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-[#181611]/55"><Link href="/destinations" className="hover:text-[#181611]">Destinations</Link><Link href="/packages" className="hover:text-[#181611]">Packages</Link><Link href="/events" className="hover:text-[#181611]">Events</Link><Link href="/blog" className="hover:text-[#181611]">Journal</Link><Link href="/about" className="hover:text-[#181611]">About</Link><Link href="/contact" className="hover:text-[#181611]">Contact</Link></div></div><div className="flex flex-col justify-between gap-2 pt-6 text-[10px] font-semibold uppercase tracking-[0.12em] text-[#181611]/35 sm:flex-row"><span>© 2026 TravelQ</span><span>Travel well. Go further.</span></div></div></footer>
    </main>
  );
}
